---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: confluent
  namespace: confluent
spec:
  interval: 1m
  chart:
    spec:
      chart: confluent-for-kubernetes
      sourceRef:
        kind: HelmRepository
        name: confluent-helm
        namespace: flux-system